api:
  adminAccount:
    passwordHash: $2y$10$MPoQdUlu9mnUsJeZrjF5euxu0MJfZXOuwqMP63eQQTZSF5Vh7og.S
    tokenSigningKey: oMJBBmr49BuYVmDw6ffxajxHf1yFESUe
    tokenTTL: 24h
controller:
  logLevel: DEBUG
